name: unidti
channels:
  - pytorch
  - nvidia
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.26.3
  - pandas=2.3.2
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - tqdm
  - prettytable
  - yacs
  - einops
  - networkx=3.2.1
  - rdkit=2025.03.5
  - dill
  - packaging
  - cudatoolkit=12.4
  - pytorch=2.6.0
  - torchvision=0.21.0
  - torchaudio=2.6.0
  - pytorch-cuda=12.4
  - dgl=2.4.0  
  - pip:
      - dgllife==0.3.2
      - matplotlib==3.9.4   
      - seaborn==0.13.2     
      - ipython             
