# configs.py
# Author  : Ethan Huang
# File    : configs.py
# Time    : 2026/3/25

from yacs.config import CfgNode as CN

_C = CN()

# Drug feature extractor
_C.DRUG = CN()
_C.DRUG.NODE_IN_FEATS = 75
_C.DRUG.PADDING = True
_C.DRUG.HIDDEN_LAYERS = [128, 128, 128]
_C.DRUG.NODE_IN_EMBEDDING = 128
_C.DRUG.MAX_NODES = 290

# Multi-granularity parameters
_C.DRUG.MULTIGRAIN = CN()
_C.DRUG.MULTIGRAIN.ENABLE = True  
_C.DRUG.MULTIGRAIN.MAX_COARSE_NODES = 50
_C.DRUG.MULTIGRAIN.COA_RSE_NODE_DIM = 15
_C.DRUG.MULTIGRAIN.ATOM_DIM = 34
_C.DRUG.MULTIGRAIN.ECFP_DIM = 1024
_C.DRUG.MULTIGRAIN.DESC_DIM = 200
_C.DRUG.MULTIGRAIN.CROSS_SCALE_INTERACTION = True
_C.DRUG.MULTIGRAIN.USE_GLOBAL_PROP = True
_C.DRUG.MULTIGRAIN.USE_COARSE = True 

# Drug sequence encoder parameters
_C.DRUG.SEQUENCE = CN()
_C.DRUG.SEQUENCE.ENABLE = True
_C.DRUG.SEQUENCE.SMILES_VOCAB_SIZE = 68
_C.DRUG.SEQUENCE.IUPAC_VOCAB_SIZE = 66
_C.DRUG.SEQUENCE.EMBEDDING_DIM = 128
_C.DRUG.SEQUENCE.HIDDEN_DIM = 128
_C.DRUG.SEQUENCE.NUM_LAYERS = 2
_C.DRUG.SEQUENCE.MAX_SMILES_LEN = 200
_C.DRUG.SEQUENCE.MAX_IUPAC_LEN = 200
_C.DRUG.SEQUENCE.DROPOUT = 0.3
_C.DRUG.SEQUENCE.USE_BILSTM = True

# Protein feature extractor
_C.PROTEIN = CN()
_C.PROTEIN.NUM_FILTERS = [128, 128, 128]
_C.PROTEIN.EMBEDDING_DIM = 128
_C.PROTEIN.NUM_HEAD = 8
_C.PROTEIN.PADDING = True
_C.PROTEIN.MAX_LEN = 1200

# Protein graph neural network parameters
_C.PROTEIN.GNN = CN()
_C.PROTEIN.GNN.ENABLE = True
_C.PROTEIN.GNN.HIDDEN_DIM = 128
_C.PROTEIN.GNN.NUM_LAYERS = 3
_C.PROTEIN.GNN.DROPOUT = 0.3
_C.PROTEIN.GNN.GCN_TYPE = 'dgl'  # 'dgl' or 'pyg'

# CrossIntention feature fusion
_C.CROSSINTENTION = CN()
_C.CROSSINTENTION.LAYER = 1
_C.CROSSINTENTION.NUM_HEAD = 8
_C.CROSSINTENTION.EMBEDDING_DIM = 128

# MLP decoder
_C.DECODER = CN()
_C.DECODER.NAME = "MLP"
_C.DECODER.IN_DIM = 256
_C.DECODER.HIDDEN_DIM = 512
_C.DECODER.OUT_DIM = 128
_C.DECODER.BINARY = 1

# SOLVER
_C.SOLVER = CN()
_C.SOLVER.MAX_EPOCH = 50
_C.SOLVER.BATCH_SIZE = 128
_C.SOLVER.NUM_WORKERS = 34
_C.SOLVER.LR = 1e-4
_C.SOLVER.USE_LD = True
_C.SOLVER.LR_DECAY = 0.5
_C.SOLVER.DECAY_INTERVAL = 25
_C.SOLVER.WEIGHT_DECAY = 1e-5
_C.SOLVER.SEED = 555

# RESULT
_C.RESULT = CN()
_C.RESULT.OUTPUT_DIR = r"/home/shaoxin/uni-dta/BINDTI/BINDTI/output/result/labeled/biosnap/60/seed555"
_C.RESULT.SAVE_MODEL = True

def get_cfg_defaults():
    return _C.clone()